### ISSUE TITLE
Find '됫' also

### ISSUE THREAD

**Issue by tribela** [yous/dwaet#2]
"됫" is also famous typo for "됐"
(How about "됏"?)

**Comment by yous** [comment]
There are several words [containing '됫'](http://dic.naver.com/search.nhn?dicQuery=됫*&query=됫*&target=dic&ie=utf8&query_utf=&isOnlyViewEE=), so extra filtering is needed. But it seems that there are no words [containing '됏'](http://dic.naver.com/search.nhn?dicQuery=됏*&query=됏*&target=dic&ie=utf8&query_utf=&isOnlyViewEE=), so I'll consider adding it. Any pull requests related this issues are welcome!

**Comment by yous** [comment]
Also there are some usage of '됏':

> 하읏... 안 됏....!

https://twitter.com/x_nuk/status/519057683635138560

**Comment by yous** [comment]
Now it also searches '됫' by https://github.com/yous/dwaet/commit/37e1e55922f8caf09f1790e3deaaf4ecd39a20b6.

**Comment by yous** [comment]
Closed via https://github.com/yous/dwaet/commit/37e1e55922f8caf09f1790e3deaaf4ecd39a20b6.

**Comment by yous** [comment]
We may search '됏', but it should come with grammatic checks. Closing this for now.
